---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongo-root-password: AgBBlXpxuB/9W+iBlUY9Fc6XDUINMzlX+Z4Yellm3avrUDws9YZ9id3iXbOnqiQ2msFShpQ+LZ6+GZunJIjHAFmb3mUY8ywWv9WLKAEEyDOjqS6aFpjEitdUE/1x7KAJBwbMmG5OtvJchc5IQTaO7vvaWXXO6QDDfvos6mCNxHtRuC/mjqspw9z7tRMdLB41Ws2X7+FDWsDne/v0CTM72l63pfkOAzHFkb+EZtgTpk1wAkUhdeDW0OWaBokm8Cvobh5L165ACdzM/LBPPVRa+ovTbpJuYrq6G3WvfIi1nuWsnVBpLoSiv2Twc+/EXIxEhhWt20cnU4Y2uQ2uA2gVS0q0LWYAVsWI3CMBzqUrDiNtVANuTKON9WtAMy+sYuGtcICZsXg53l1UkMqNVJUnnrS1JLmNimRw09vId5Ba9hr/Gw8rIM0TyaYslTgn/94YmCDzNz6YjC4Fx21UH1I6NJHev9bDQKkHlkqDpiX6riWm4ZSIQhPXs61rL6gjg+bvvAIBooVRF+DJJwpPyfJg8I6SR1xB6cdp960dlwxwZ6wRLE+vBjyZJoPMQXE10+WNfgqD+oevhCWMcaSJ/pZ+LlUb+D74/FQizK6d+sD6swaDPuxPUr1RoOmPPOKTBuLHwPRbX7rFSHI7OV/6rkpg4v5uq0gwnwy+07V/B+wT1Sx8XVFAGZeUYwnmZ9tB+gs/IDw4uPNfS9XixQ==
    mongo-root-username: AgB9COxx/hHF7UtffNyUoq6hT4D0xAtqUvh29fZI76nseU9IA2I5B94Gzr+/LX9QnB30wqw193f0Q+EyEsBjJsT6TC3rOg7nvSCOniz9qKjLe09sW6GShhQS5Amp2CFLo0GgPVvOxNWTswSUzT+NvKGe3E2cxZMGp4k9oyoCONEreT8E5ajNWIGZocz5XjlIp6KsDP75bKhE5L5fZ/cEFyyfmP2FicuA8w7HChDy/NJ6TsFQzaPWCKXMMtOCMd55vPJbdCJMDwSNh1oUonkNVx5yOhfXaWZipdv2OiTL0wh+bSd9RU+53J0eJafEK94V1uH1bDIqk9g81WLaGqJ5TmvEJRydZ+wCxODMWvf1mwXhhwmp78iHDx40UnHAUu2rh7x9m4dEuhH7X1Bma55vbpg8wwEikEtgK0iBy8U46W5kXjnb9o0HAJyBxmJF33z6z/zN+DTHhpa+eHEJg2Qz5soJpM13JVC58f3LgCBqGzqIJ01/ybhnfLxB6GiHkEnIO4ZveOi0MWpzNe5KWzCt7f6/Gm5/m3UG2d+7fFlsNqhVNGiDoLK7YHqxYNMt/gFvvvXTImtvQx4DW87MgvYNUd7EpF7+3aWN2rHIjWuPPPPDuUO8IPk1RhN684FWJhhiAcT7jKf7MxCHid74WTtm09VIJvNWknJoavb56vyvJiBzuosfemo7cYwhUYvpYKrMbQsq7YAS
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
