---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongo-root-password: AgCtLW3L+1E53wzjBgJQAH81FKph7p1maBa90zHdYtZdFmR6ggSNRgzjOnrIf2AaWJhkv35LuWk+hDQksiJjmlSP94kCovFBFjgftMaNQPaDszQvlVuuQ1M9PHNcGZH2rG+HvutZzbfsHOpE6iWQpE8tQ5juC0xoDzpIO0POQwbbypMBgvh2y2T7wLBBVS0rEs8/n0lPgGlx6I3fdTjdqr5sY6C81TtDuk1d9LLLe/gMaCobWFtW2ci+YcTqMVBNyGuiaR8JpqSE12mf93iDj6PSSrk2oT130caRrvJSzgkqWwckiAXqLn7I97IsVlBgAQCZrk8q2Ekc48syxdwSeDu59apmIwEV0f4SZrtMviXLbQ/hqz4G1GDDfHKpEjzCYMxnmyhSCdF6h11dwN04jXUQDeNS2huDIxfBn1m2pw3nAQYfHXPsDsuHQR3JvhUw35wORmKiPqQfYjtSkUQDBd3A8s+1ZI5r9WBYF/Lu7J3+ONWv59fa0rzgOUCpGX/aBN8Md4r+WDj+urg2rzXbtiQkua9iu/pBdz12cRN2TS+r/eI6/Nw4dRlGjADpSFiLOLUfIIL+tzbIj4701v9z0Y4zRKxpkTDcCHK7T7DRegDl6O69IomiLTQC+LsXEaSz1A5X6c3rjWv02UR7UuPJcZ/tBMQUFX9dN3LbnpbZnsFgDcFwAXusHwoZyKbSb6cogkvB2krpXfHHhg==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
