---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongo-root-password: AgC1koLkUAQAEMgRHSTakiuORudnYGhYEFC55KgIrPU4SM0QgOYnDCE+YAy39lpyaKWApIpePTcs59ji94PlRstLW1mCP7uZYRsQe6GqU66znYQnN/LbE4T6dbE9heeq5SyOdw04ENoStDE134jXSCFJI6CKYQz07UELD3HfIlq2P0U9z6SXfZl2E9+epqFimBEu6sQ6hsH1t7r6eA5H6PicRFhDPpHCdw42fKxOwTGThqYlkcl3UiZ+KjMnwLHz+Hzhd5ZcDvLVrk1Qz/qCGXaLx+a5Gp3nfg/I4Qy/yIA/eU5ghLWsKcnfwW9J6Zhg3nmYqEZhBq930PPu7CR33EhYICP9fd7DQxPvUX8aBgQc9F/YvuVzrVVvUjP4MykjB6FExbynSOY3CaPVz+1vz+UJczK2t8jCjY5isTaLrLyah0z1Xq5Nc02n9UgOF3Ai10PE5Te6o9Gpn3jsSSVv8f6yHrYy17a+bAbVY2J705jD/vbmpHm8KHSEJwjSXPpWQLKRuTxu0Qn8UlaJU7S0vanfk0jSjDGBH6fsQUCyZA83l7+uPLTi1UAxMhE7I5cSZBdOa7aCCLk4YALo7YbwIWSrcnKP41cq9A34n2Oh7tJxDEXxT+xz4waTBxiO9p++aQKoFN1/AuTnz9wE5bZZnFwu5y4YfbSb9xNcaT4ztSVYSZCu2wan8TfD25dzxtfOV7+F/PnIw6pnUg==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
