pipeline {
    agent none

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        DOCKER_USER = 'premkoredla'
        FRONTEND_IMAGE = "${DOCKER_USER}/frontend"
        BACKEND_IMAGE = "${DOCKER_USER}/backend"
    }

    stages {
        stage('Lint') {
            agent {
                docker {
                    image 'node:18'
                    args '-v $HOME/.npm:/home/node/.npm'
                }
            }
            steps {
                sh 'npm ci --prefix frontend && npm run lint --prefix frontend'
                sh 'npm ci --prefix backend && npm run lint --prefix backend'
            }
        }

        stage('Unit Tests') {
            agent {
                docker {
                    image 'node:18'
                    args '-v $HOME/.npm:/home/node/.npm'
                }
            }
            steps {
                sh 'npm test --prefix frontend'
                sh 'npm test --prefix backend'
            }
        }

        stage('Build Docker Images') {
            agent {
                docker {
                    image 'docker:24.0'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh "docker build -t $FRONTEND_IMAGE:${BUILD_NUMBER} ./frontend"
                sh "docker build -t $BACKEND_IMAGE:${BUILD_NUMBER} ./backend"
            }
        }

        stage('Push to Docker Hub') {
            agent {
                docker {
                    image 'docker:24.0'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
                    sh "docker push $FRONTEND_IMAGE:${BUILD_NUMBER}"
                    sh "docker push $BACKEND_IMAGE:${BUILD_NUMBER}"
                }
            }
        }

        stage('Update Manifests in Git') {
            agent { label 'docker' }
            steps {
                sh """
                sed -i 's|image: ${FRONTEND_IMAGE}:.*|image: ${FRONTEND_IMAGE}:${BUILD_NUMBER}|' manifests/frontend-deployment.yaml
                sed -i 's|image: ${BACKEND_IMAGE}:.*|image: ${BACKEND_IMAGE}:${BUILD_NUMBER}|' manifests/backend-deployment.yaml

                git config --global user.email ""
                git config --global user.name ""
                git add manifests/*.yaml
                git commit -m "Update images to build ${BUILD_NUMBER}"
                git push origin main
                """
            }
        }
    }
}
