apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: premkoredla/frontend:9e76d945faf25cca12e419040f115467021aaae1
        ports:
        - containerPort: 80
