apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: premkoredla/frontend:105c48584fe6727bcfa54c2d6ba0468bd2ad5536
        ports:
        - containerPort: 80
