apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: premkoredla/frontend:cdd8c73ef18e29d77b762a965e55e314605bf8e2
        ports:
        - containerPort: 80
